<a href="https://colab.research.google.com/github/mohyunyang/MyStudy/blob/master/SPSS_%3ECSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pyreadstat

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyreadstat
  Downloading pyreadstat-1.1.7-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)
     |████████████████████████████████| 2.5 MB 13.8 MB/s
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.7/dist-packages (from pyreadstat) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.2.0->pyreadstat) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.2.0->pyreadstat) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.2.0->pyreadstat) (1.15.0)
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.1.7

In [2]:
import pandas as pd

In [7]:
data1 = pd.read_spss("klowf_07_p.sav")
data1.head()

,OPID,Pwave,PwaveA,PwaveB,PDAY,PweiL,PweiC,PweiCA,H01HHID,H02HHID,...,H05DB04,H05DB05,H05DB06,H05DB07,H05DB10,H05DB11,H05FC,H05LE12,H05LE13,H05LE15
0,101.0,7차,기존 응답,7차 기존 응답자,2018-11-06,8473.707425,7191.590725,4451.820241,1.0,1.0,...,아니오,NaN,NaN,아니오,NaN,NaN,조금 어려운 편이다,의료비,교통/통신비,
1,202.0,7차,기존 응답,7차 기존 응답자,2019-04-11,6021.431199,5360.789916,2848.372483,2.0,2.0,...,아니오,NaN,NaN,아니오,NaN,NaN,조금 어려운 편이다,식비(식료품비),교육비,
2,302.0,7차,기존 응답,7차 기존 응답자,2019-03-11,6555.718130,5549.330162,3088.530732,3.0,3.0,...,아니오,NaN,NaN,아니오,NaN,NaN,보통이다,식비(식료품비),없음,
3,402.0,7차,기존 응답,7차 기존 응답자,2019-03-28,1218.705135,1135.059631,967.126734,4.0,4.0,...,아니오,NaN,NaN,아니오,NaN,NaN,여유가 있는 편이다,교육비,교통/통신비,
4,502.0,7차,기존 응답,7차 기존 응답자,2018-11-07,4205.183019,3568.916612,2209.271331,5.0,5.0,...,아니오,NaN,NaN,아니오,NaN,NaN,여유가 있는 편이다,교통/통신비,식비(식료품비),

In [8]:
target1 = data1[["Pwave","PwaveB","H05FC","H05LE12","H05LE13"]]
target1.head()

  Pwave     PwaveB       H05FC   H05LE12   H05LE13
0    7차  7차 기존 응답자  조금 어려운 편이다       의료비    교통/통신비
1    7차  7차 기존 응답자  조금 어려운 편이다  식비(식료품비)       교육비
2    7차  7차 기존 응답자        보통이다  식비(식료품비)        없음
3    7차  7차 기존 응답자  여유가 있는 편이다       교육비    교통/통신비
4    7차  7차 기존 응답자  여유가 있는 편이다    교통/통신비  식비(식료품비)

In [9]:
target1.columns = ["차수","기존여부","살림살이","1차비용","2차비용"]
target1.head()

   차수       기존여부        살림살이      1차비용      2차비용
0  7차  7차 기존 응답자  조금 어려운 편이다       의료비    교통/통신비
1  7차  7차 기존 응답자  조금 어려운 편이다  식비(식료품비)       교육비
2  7차  7차 기존 응답자        보통이다  식비(식료품비)        없음
3  7차  7차 기존 응답자  여유가 있는 편이다       교육비    교통/통신비
4  7차  7차 기존 응답자  여유가 있는 편이다    교통/통신비  식비(식료품비)

In [10]:
target1.to_csv("target1.csv.index=False")